# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(name:"Mandy")

Country.create(name:"France",code:"fr")
Country.create(name:"Russia", code:"ru")

Country.create(name:"United States",code:"us")
Country.create(name:"Egypt",code:'eg')

Country.create(name:"China",code:'cn')
Country.create(name:"Venezuela",code:'ve')
#-------
Country.create(name:"United Arab Emirates",code:"ae")
Country.create(name:"Argentina", code:"ar")
Country.create(name:"Austria",code:"at")
Country.create(name:"Australia",code:'au')
Country.create(name:"Belgium",code:'be')
Country.create(name:"Bulgaria",code:'bg')
Country.create(name:"Brazil",code:'br')
Country.create(name:"Canada",code:'ca')
#-------
Country.create(name:"Switzerlands",code:"ch")
Country.create(name:"Colombia", code:"co")
Country.create(name:"Cuba",code:"cu")
Country.create(name:"Czechia",code:'cz')
Country.create(name:"Germany",code:'de')
Country.create(name:"United Kingdom",code:'gb')
Country.create(name:"Greece",code:'gr')
Country.create(name:"Hungary",code:'hu')
#-------
Country.create(name:"Indonesia",code:"id")
Country.create(name:"Ireland", code:"ie")
Country.create(name:"Israel",code:"il")
Country.create(name:"India",code:'in')
Country.create(name:"Italy",code:'it')
Country.create(name:"Japan",code:'jp')
Country.create(name:"South Korea",code:'kr')
Country.create(name:"Lithuania",code:'lt')
#--------
Country.create(name:"Latvia",code:"lv")
Country.create(name:"Morocco", code:"ma")
Country.create(name:"Mexico",code:"mx")
Country.create(name:"Malaysia",code:'my')
Country.create(name:"Nigeria",code:'ng')
Country.create(name:"Netherlands",code:'nl')
Country.create(name:"Norway",code:'no')
Country.create(name:"New Zealand",code:'nz')
Country.create(name:"Philippines",code:"ph")
Country.create(name:"Poland", code:"pl")
Country.create(name:"Portugal",code:"pt")
Country.create(name:"Romania",code:'ro')
Country.create(name:"Serbia",code:'rs')
Country.create(name:"Sweden",code:'se')
Country.create(name:"Singapore",code:'sg')
#---
Country.create(name:"Slovenia",code:"si")
Country.create(name:"Slovakia",code:'sk')
Country.create(name:"Thailand",code:'th')
Country.create(name:"Turkey",code:'tr')
Country.create(name:"Taiwan",code:'tw')
Country.create(name:"Ukraine",code:'ua')
Country.create(name:"South Africa",code:"za")

Country.create(name:"Kenya",code:'')
Country.create(name:"Jordan",code:'')
Country.create(name:"Democratic Republic of the Congo",code:"")
Country.create(name:"Iran",code:"")
Country.create(name:"Tanzania",code:"")
Country.create(name:"Myanmar",code:"")
Country.create(name:"Pakistan",code:"")
Country.create(name:"Bangladesh",code:"")
Country.create(name:"Ethiopia",code:"")
Country.create(name:"Vietnam",code:"")

Country.create(name:"Spain",code:"")
Country.create(name:"Uganda",code:"")
Country.create(name:"Algeria",code:"")
Country.create(name:"Sudan",code:"")
Country.create(name:"Iraq",code:"")
Country.create(name:"Afghanistan",code:"")
Country.create(name:"Saudi Arabia",code:"")
Country.create(name:"Peru",code:"")


Country.create(name:"Uzbekistan",code:"")
Country.create(name:"Angola",code:"")
Country.create(name:"Mozambique",code:"")
Country.create(name:"Ghana",code:"")
Country.create(name:"Nepal",code:"")
Country.create(name:"Yemen",code:"")
Country.create(name:"Madagascar",code:"")
Country.create(name:"North Korea",code:"")
Country.create(name:"Côte d'Ivoire",code:"")

Country.create(name:"Cameroon",code:"")
Country.create(name:"Sri Lanka",code:"")
Country.create(name:"Burkina Faso",code:"")
Country.create(name:"Malawi",code:"")
Country.create(name:"Mali",code:"")
Country.create(name:"Kazakhstan",code:"")
Country.create(name:"Syria",code:"")
Country.create(name:"Chile",code:"")
Country.create(name:"Zambia",code:"")

Country.create(name:"Guatemala",code:"")
Country.create(name:"Zimbabwe",code:"")
Country.create(name:"Ecuador",code:"")
Country.create(name:"Senegal",code:"")
Country.create(name:"Cambodia",code:"")
Country.create(name:"Chad",code:"")
Country.create(name:"Somalia",code:"")
Country.create(name:"Guinea",code:"")
Country.create(name:"South Sudan",code:"")
Country.create(name:"Rwanda",code:"")
Country.create(name:"Benin",code:"")
Country.create(name:"Tunisia",code:"")
Country.create(name:"Burundi",code:"")
Country.create(name:"Bolivia",code:"")
Country.create(name:"Haiti",code:"")
Country.create(name:"Dominican Republic",code:"")
Country.create(name:"Azerbaijan",code:"")
Country.create(name:"Honduras",code:"")
Country.create(name:"Belarus",code:"")
Country.create(name:"Tajikistan",code:"")

Country.create(name:"Papua New Guinea",code:"")
Country.create(name:"Togo",code:"")
Country.create(name:"Sierra Leone",code:"")
Country.create(name:"Laos",code:"")
Country.create(name:"Paraguay",code:"")
Country.create(name:"Libya",code:"")
Country.create(name:"El Salvador",code:"")
Country.create(name:"Nicaragua",code:"")
Country.create(name:"Kyrgyzstan",code:"")
Country.create(name:"Lebanon",code:"")
Country.create(name:"Turkmenistan",code:"")
Country.create(name:"Denmark",code:"")
Country.create(name:"Finland",code:"")
Country.create(name:"Republic of Congo",code:"")
Country.create(name:"Eritrea",code:"")
Country.create(name:"State of Palestine",code:"") #EDGE CASE NOT ON MAP
Country.create(name:"Oman",code:"")
Country.create(name:"Costa Rica",code:"")

Country.create(name:"Liberia",code:"")
Country.create(name:"Central African Republic",code:"")
Country.create(name:"Mauritania",code:"")
Country.create(name:"Kuwait",code:"")
Country.create(name:"Panama",code:"")
Country.create(name:"Croatia",code:"")
Country.create(name:"Moldova",code:"")
Country.create(name:"Geogia",code:"")
Country.create(name:"Bosnia and Herzegovina",code:"")
Country.create(name:"Uraguay",code:"")
Country.create(name:"Mongolia",code:"")
Country.create(name:"Albania",code:"")
Country.create(name:"Armenia",code:"")

Country.create(name:"Jamaica",code:"")
Country.create(name:"Qatar",code:"")
Country.create(name:"Namibia",code:"")
Country.create(name:"Botswana",code:"")
Country.create(name:"Lesotho",code:"")
Country.create(name:"Gambia",code:"")
Country.create(name:"Gabon",code:"")
Country.create(name:"Macedonia",code:"")
Country.create(name:"Guinea Bissau",code:"")
Country.create(name:"Bahrain",code:"")
Country.create(name:"Swaziland",code:"")

#150
Country.create(name:"Trinidad and Tobago",code:"")
Country.create(name:"Equatorial Guinea",code:"")
Country.create(name:"East Timor",code:"")
Country.create(name:"Estonia",code:"")
Country.create(name:"Mauritius",code:"")
Country.create(name:"Cyprus",code:"")
Country.create(name:"Djibouti",code:"")
Country.create(name:"Fiji",code:"")
Country.create(name:"Comoros",code:"")
Country.create(name:"Bhutan",code:"")
Country.create(name:"Guyana",code:"")
Country.create(name:"Solomon Islands",code:"")
Country.create(name:"Montenegro",code:"")
Country.create(name:"Luxembourg",code:"")
Country.create(name:"Suriname",code:"")

Country.create(name:"Cape Verde",code:"")
Country.create(name:"Maldives",code:"")
Country.create(name:"Brunei",code:"")
Country.create(name:"Malta",code:"")
Country.create(name:"Bahamas",code:"")
Country.create(name:"Belize",code:"")
Country.create(name:"Iceland",code:"")
Country.create(name:"Vanuatu",code:"")
Country.create(name:"Barbados",code:"")
Country.create(name:"Sao Tome and Principe",code:"")
Country.create(name:"Samoa",code:"")
Country.create(name:"Saint Lucia",code:"")
Country.create(name:"Kiribati",code:"")
Country.create(name:"Saint Vincent and the Grenadines",code:"")
Country.create(name:"Tonga",code:"")
Country.create(name:"Grenada",code:"")
Country.create(name:"Micronesia",code:"")
Country.create(name:"Antigua and Barbuda",code:"")
Country.create(name:"Seychelles",code:"")
Country.create(name:"Andorra",code:"")
Country.create(name:"Dominica",code:"")
Country.create(name:"Saint Kitts and Nevis",code:"")
Country.create(name:"Marshall Islands",code:"")
Country.create(name:"Monaco",code:"")
Country.create(name:"Liechtenstein",code:"")
Country.create(name:"San Marino",code:"")
Country.create(name:"Palau",code:"")
Country.create(name:"Tuvalu",code:"")
Country.create(name:"Nauru",code:"")
Country.create(name:"Vatican",code:"")


UserCountry.create(user_id:1, country_id:1)
UserCountry.create(user_id:1, country_id:4)
UserCountry.create(user_id:1, country_id:7)
UserCountry.create(user_id:1, country_id:5)
