# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(username:"Mandy",password:"helloworld")

Country.create(name:"France",code:"fr",flag:"fr")
Country.create(name:"Russia", code:"ru",flag:"ru")

Country.create(name:"United States",code:"us",flag:"us")
Country.create(name:"Egypt",code:'eg',flag:'eg')

Country.create(name:"China",code:'cn',flag:'cn')
Country.create(name:"Venezuela",code:'ve',flag:'ve')
#-------
Country.create(name:"United Arab Emirates",code:"ae",flag:"ae")
Country.create(name:"Argentina", code:"ar",flag:"ar")
Country.create(name:"Austria",code:"at",flag:"at")
Country.create(name:"Australia",code:'au',flag:"au")
Country.create(name:"Belgium",code:'be',flag:"be")
Country.create(name:"Bulgaria",code:'bg',flag:"bg")
Country.create(name:"Brazil",code:'br',flag:"br")
Country.create(name:"Canada",code:'ca',flag:"ca")
#-------
Country.create(name:"Switzerland",code:"ch",flag:"ch")
Country.create(name:"Colombia", code:"co",flag:"co")
Country.create(name:"Cuba",code:"cu",flag:"cu")
Country.create(name:"Czechia",code:'cz',flag:"cz")
Country.create(name:"Germany",code:'de',flag:"de")
Country.create(name:"United Kingdom",code:'gb',flag:"gb")
Country.create(name:"Greece",code:'gr',flag:"gr")
Country.create(name:"Hungary",code:'hu',flag:"hu")
#-------
Country.create(name:"Indonesia",code:"id",flag:"id")
Country.create(name:"Ireland", code:"ie",flag:"ie")
Country.create(name:"Israel",code:"il",flag:"il")
Country.create(name:"India",code:'in',flag:"in")
Country.create(name:"Italy",code:'it',flag:"it")
Country.create(name:"Japan",code:'jp',flag:"jp")
Country.create(name:"South Korea",code:'kr',flag:"kr")
Country.create(name:"Lithuania",code:'lt',flag:"lt")
#--------
Country.create(name:"Latvia",code:"lv",flag:"lv")
Country.create(name:"Morocco", code:"ma",flag:"ma")
Country.create(name:"Mexico",code:"mx",flag:"mx")
Country.create(name:"Malaysia",code:'my',flag:"my")
Country.create(name:"Nigeria",code:'ng',flag:"ng")
Country.create(name:"Netherlands",code:'nl',flag:"nl")
Country.create(name:"Norway",code:'no',flag:"no")
Country.create(name:"New Zealand",code:'nz',flag:"nz")
Country.create(name:"Philippines",code:"ph",flag:"ph")
Country.create(name:"Poland", code:"pl",flag:"pl")
Country.create(name:"Portugal",code:"pt",flag:"pt")
Country.create(name:"Romania",code:'ro',flag:"ro")
Country.create(name:"Serbia",code:'rs',flag:"rs")
Country.create(name:"Sweden",code:'se',flag:"se")
Country.create(name:"Singapore",code:'sg',flag:"sg")
#---
Country.create(name:"Slovenia",code:"si",flag:"si")
Country.create(name:"Slovakia",code:'sk',flag:"sk")
Country.create(name:"Thailand",code:'th',flag:"th")
Country.create(name:"Turkey",code:'tr',flag:"tr")
Country.create(name:"Taiwan",code:'tw',flag:"tw")
Country.create(name:"Ukraine",code:'ua',flag:"ua")
Country.create(name:"South Africa",code:"za",flag:"za")

Country.create(name:"Kenya",code:'',flag:"ke")
Country.create(name:"Jordan",code:'jo',flag:"jo")
Country.create(name:"Democratic Republic of the Congo",code:"",flag:"cd")
Country.create(name:"Iran",code:"",flag:"ir")
Country.create(name:"Tanzania",code:"",flag:"tz")
Country.create(name:"Myanmar",code:"",flag:"mm")
Country.create(name:"Pakistan",code:"",flag:"pk")
Country.create(name:"Bangladesh",code:"",flag:"bd")
Country.create(name:"Ethiopia",code:"",flag:"et")
Country.create(name:"Vietnam",code:"",flag:"vn")

Country.create(name:"Spain",code:"",flag:"es")
Country.create(name:"Uganda",code:"",flag:"ug")
Country.create(name:"Algeria",code:"",flag:"dz")
Country.create(name:"Sudan",code:"",flag:"sd")
Country.create(name:"Iraq",code:"",flag:"iq")
Country.create(name:"Afghanistan",code:"",flag:"af")
Country.create(name:"Saudi Arabia",code:"",flag:"sa")
Country.create(name:"Peru",code:"",flag:"pe")


Country.create(name:"Uzbekistan",code:"",flag:"uz")
Country.create(name:"Angola",code:"",flag:"ao")
Country.create(name:"Mozambique",code:"",flag:"mz")
Country.create(name:"Ghana",code:"",flag:"gh")
Country.create(name:"Nepal",code:"",flag:"np")
Country.create(name:"Yemen",code:"",flag:"ye")
Country.create(name:"Madagascar",code:"",flag:"mg")
Country.create(name:"North Korea",code:"",flag:"kp")
Country.create(name:"Ivory Coast",code:"",flag:"ci")

Country.create(name:"Cameroon",code:"",flag:"cm")
Country.create(name:"Sri Lanka",code:"",flag:"lk")
Country.create(name:"Burkina Faso",code:"",flag:"bf")
Country.create(name:"Malawi",code:"",flag:"mw")
Country.create(name:"Mali",code:"",flag:"ml")
Country.create(name:"Kazakhstan",code:"",flag:"kz")
Country.create(name:"Syria",code:"",flag:"sy")
Country.create(name:"Chile",code:"",flag:"cl")
Country.create(name:"Zambia",code:"",flag:"zm")

Country.create(name:"Guatemala",code:"",flag:"gt")
Country.create(name:"Zimbabwe",code:"",flag:"zw")
Country.create(name:"Ecuador",code:"",flag:"ec")
Country.create(name:"Senegal",code:"",flag:"sn")
Country.create(name:"Cambodia",code:"",flag:"kh")
Country.create(name:"Chad",code:"",flag:"td")
Country.create(name:"Somalia",code:"",flag:"so")
Country.create(name:"Guinea",code:"",flag:"gn")
Country.create(name:"South Sudan",code:"",flag:"ss")
Country.create(name:"Rwanda",code:"",flag:"rw")
Country.create(name:"Benin",code:"",flag:"bj")
Country.create(name:"Tunisia",code:"",flag:"tn")
Country.create(name:"Burundi",code:"",flag:"bi")
Country.create(name:"Bolivia",code:"",flag:"bo")
Country.create(name:"Haiti",code:"",flag:"ht")
Country.create(name:"Dominican Republic",code:"",flag:"do")
Country.create(name:"Azerbaijan",code:"",flag:"az")
Country.create(name:"Honduras",code:"",flag:"hn")
Country.create(name:"Belarus",code:"",flag:"by")
Country.create(name:"Tajikistan",code:"",flag:"tj")

Country.create(name:"Papua New Guinea",code:"",flag:"pg")
Country.create(name:"Togo",code:"",flag:"tg")
Country.create(name:"Sierra Leone",code:"",flag:"sl")
Country.create(name:"Laos",code:"",flag:"la")
Country.create(name:"Paraguay",code:"",flag:"py")
Country.create(name:"Libya",code:"",flag:"ly")
Country.create(name:"El Salvador",code:"",flag:"sv")
Country.create(name:"Nicaragua",code:"",flag:"ni")
Country.create(name:"Kyrgyzstan",code:"",flag:"kg")
Country.create(name:"Lebanon",code:"",flag:"lb")
Country.create(name:"Turkmenistan",code:"",flag:"tm")
Country.create(name:"Denmark",code:"",flag:"dk")
Country.create(name:"Finland",code:"fi",flag:"fi")
Country.create(name:"Republic of Congo",code:"",flag:"cg")
Country.create(name:"Eritrea",code:"",flag:"er")
Country.create(name:"State of Palestine",code:"",flag:"ps") #EDGE CASE NOT ON MAP
Country.create(name:"Oman",code:"",flag:"om")
Country.create(name:"Costa Rica",code:"",flag:"cr")

Country.create(name:"Liberia",code:"",flag:"lr")
Country.create(name:"Central African Republic",code:"",flag:"cf")
Country.create(name:"Mauritania",code:"",flag:"mr")
Country.create(name:"Kuwait",code:"",flag:"kw")
Country.create(name:"Panama",code:"",flag:"pa")
Country.create(name:"Croatia",code:"",flag:"hr")
Country.create(name:"Moldova",code:"",flag:"md")
Country.create(name:"Georgia",code:"",flag:"ge")
Country.create(name:"Bosnia and Herzegovina",code:"",flag:"ba")
Country.create(name:"Uruguay",code:"",flag:"uy")
Country.create(name:"Mongolia",code:"",flag:"mn")
Country.create(name:"Albania",code:"",flag:"al")
Country.create(name:"Armenia",code:"",flag:"am")

Country.create(name:"Jamaica",code:"",flag:"jm")
Country.create(name:"Qatar",code:"",flag:"qa")
Country.create(name:"Namibia",code:"",flag:"na")
Country.create(name:"Botswana",code:"",flag:"bw")
Country.create(name:"Lesotho",code:"",flag:"ls")
Country.create(name:"Gambia",code:"",flag:"gm")
Country.create(name:"Gabon",code:"",flag:"ga")
Country.create(name:"Macedonia",code:"",flag:"mk")
Country.create(name:"Guinea Bissau",code:"",flag:"gw")
Country.create(name:"Bahrain",code:"",flag:"bh")
Country.create(name:"Swaziland",code:"",flag:"sz")

#150
Country.create(name:"Trinidad and Tobago",code:"",flag:"tt")
Country.create(name:"Equatorial Guinea",code:"",flag:"gq")
Country.create(name:"East Timor",code:"",flag:"tl")
Country.create(name:"Estonia",code:"",flag:"ee")
Country.create(name:"Mauritius",code:"",flag:"mu")
Country.create(name:"Cyprus",code:"",flag:"cy")
Country.create(name:"Djibouti",code:"",flag:"dj")
Country.create(name:"Fiji",code:"",flag:"fj")
Country.create(name:"Comoros",code:"",flag:"km")
Country.create(name:"Bhutan",code:"",flag:"bt")
Country.create(name:"Guyana",code:"",flag:"gy")
Country.create(name:"Solomon Islands",code:"",flag:"sb")
Country.create(name:"Montenegro",code:"",flag:"me")
Country.create(name:"Luxembourg",code:"",flag:"lu")
Country.create(name:"Suriname",code:"",flag:"sr")

Country.create(name:"Cape Verde",code:"",flag:"cv")
Country.create(name:"Maldives",code:"",flag:"mv")
Country.create(name:"Brunei",code:"",flag:"bn")
Country.create(name:"Malta",code:"",flag:"mt")
Country.create(name:"Bahamas",code:"",flag:"bs")
Country.create(name:"Belize",code:"",flag:"bz")
Country.create(name:"Iceland",code:"",flag:"is")
Country.create(name:"Vanuatu",code:"",flag:"vu")
Country.create(name:"Barbados",code:"",flag:"bb")
Country.create(name:"Sao Tome and Principe",code:"",flag:"st")
Country.create(name:"Samoa",code:"",flag:"ws")
Country.create(name:"Saint Lucia",code:"",flag:"lc")
Country.create(name:"Kiribati",code:"",flag:"ki")
Country.create(name:"Saint Vincent and the Grenadines",code:"",flag:"vc")
Country.create(name:"Tonga",code:"",flag:"to")
Country.create(name:"Grenada",code:"",flag:"gd")
Country.create(name:"Federated States of Micronesia",code:"",flag:"fm")
Country.create(name:"Antigua and Barbuda",code:"",flag:"ag")
Country.create(name:"Seychelles",code:"",flag:"sc")
Country.create(name:"Andorra",code:"",flag:"ad")
Country.create(name:"Dominica",code:"",flag:"dm")
Country.create(name:"Saint Kitts and Nevis",code:"",flag:"kn")
Country.create(name:"Marshall Islands",code:"",flag:"mh")
Country.create(name:"Monaco",code:"",flag:"mc")
Country.create(name:"Liechtenstein",code:"",flag:"li")
Country.create(name:"San Marino",code:"",flag:"sm")
Country.create(name:"Palau",code:"",flag:"pw")
Country.create(name:"Tuvalu",code:"",flag:"tv")
Country.create(name:"Nauru",code:"",flag:"nr")
Country.create(name:"Vatican",code:"",flag:"va")
Country.create(name:"World News",code:"",flag:"https://ak6.picdn.net/shutterstock/videos/2233546/thumb/1.jpg")


UserCountry.create(user_id:1, country_id:1)
UserCountry.create(user_id:1, country_id:4)
UserCountry.create(user_id:1, country_id:7)
UserCountry.create(user_id:1, country_id:5)
